version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
    depends_on:
      - db

  db:
    image: "sqlite:latest"
    volumes:
      - ./articles.db:/app/articles.db
    environment:
      - SQLITE_DB_PATH=/app/articles.db